//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSS.Mobile.API.wsShipping {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_ShippingChargesOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_ShippingChargesMVCOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_ShippingChargesWEBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Verify_AddressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SSS.Mobile.API.Properties.Settings.Default.SPARS_DigitalEngine_wsShipping_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_ShippingChargesCompletedEventHandler get_ShippingChargesCompleted;
        
        /// <remarks/>
        public event get_ShippingChargesMVCCompletedEventHandler get_ShippingChargesMVCCompleted;
        
        /// <remarks/>
        public event get_ShippingChargesWEBCompletedEventHandler get_ShippingChargesWEBCompleted;
        
        /// <remarks/>
        public event Verify_AddressCompletedEventHandler Verify_AddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_ShippingCharges", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_ShippingCharges(string shipVia, string serviceStandard, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, object p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress) {
            object[] results = this.Invoke("get_ShippingCharges", new object[] {
                        shipVia,
                        serviceStandard,
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_Declarevalue,
                        p_TempRecords,
                        p_TotalQty,
                        p_SignatureRequiredforDelivery,
                        p_ViewDetail,
                        p_DropShipAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_ShippingChargesAsync(string shipVia, string serviceStandard, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, object p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress) {
            this.get_ShippingChargesAsync(shipVia, serviceStandard, Address1, City, State, Zip, Country, p_Declarevalue, p_TempRecords, p_TotalQty, p_SignatureRequiredforDelivery, p_ViewDetail, p_DropShipAddress, null);
        }
        
        /// <remarks/>
        public void get_ShippingChargesAsync(string shipVia, string serviceStandard, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, object p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress, object userState) {
            if ((this.get_ShippingChargesOperationCompleted == null)) {
                this.get_ShippingChargesOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_ShippingChargesOperationCompleted);
            }
            this.InvokeAsync("get_ShippingCharges", new object[] {
                        shipVia,
                        serviceStandard,
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_Declarevalue,
                        p_TempRecords,
                        p_TotalQty,
                        p_SignatureRequiredforDelivery,
                        p_ViewDetail,
                        p_DropShipAddress}, this.get_ShippingChargesOperationCompleted, userState);
        }
        
        private void Onget_ShippingChargesOperationCompleted(object arg) {
            if ((this.get_ShippingChargesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_ShippingChargesCompleted(this, new get_ShippingChargesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_ShippingChargesMVC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_ShippingChargesMVC(string shipVia, string serviceStandard, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, decimal[] p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress) {
            object[] results = this.Invoke("get_ShippingChargesMVC", new object[] {
                        shipVia,
                        serviceStandard,
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_Declarevalue,
                        p_TempRecords,
                        p_TotalQty,
                        p_SignatureRequiredforDelivery,
                        p_ViewDetail,
                        p_DropShipAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_ShippingChargesMVCAsync(string shipVia, string serviceStandard, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, decimal[] p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress) {
            this.get_ShippingChargesMVCAsync(shipVia, serviceStandard, Address1, City, State, Zip, Country, p_Declarevalue, p_TempRecords, p_TotalQty, p_SignatureRequiredforDelivery, p_ViewDetail, p_DropShipAddress, null);
        }
        
        /// <remarks/>
        public void get_ShippingChargesMVCAsync(string shipVia, string serviceStandard, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, decimal[] p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress, object userState) {
            if ((this.get_ShippingChargesMVCOperationCompleted == null)) {
                this.get_ShippingChargesMVCOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_ShippingChargesMVCOperationCompleted);
            }
            this.InvokeAsync("get_ShippingChargesMVC", new object[] {
                        shipVia,
                        serviceStandard,
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_Declarevalue,
                        p_TempRecords,
                        p_TotalQty,
                        p_SignatureRequiredforDelivery,
                        p_ViewDetail,
                        p_DropShipAddress}, this.get_ShippingChargesMVCOperationCompleted, userState);
        }
        
        private void Onget_ShippingChargesMVCOperationCompleted(object arg) {
            if ((this.get_ShippingChargesMVCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_ShippingChargesMVCCompleted(this, new get_ShippingChargesMVCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_ShippingChargesWEB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_ShippingChargesWEB(string[] MYArrserviceCode, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, string[] p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress) {
            object[] results = this.Invoke("get_ShippingChargesWEB", new object[] {
                        MYArrserviceCode,
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_Declarevalue,
                        p_TempRecords,
                        p_TotalQty,
                        p_SignatureRequiredforDelivery,
                        p_ViewDetail,
                        p_DropShipAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_ShippingChargesWEBAsync(string[] MYArrserviceCode, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, string[] p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress) {
            this.get_ShippingChargesWEBAsync(MYArrserviceCode, Address1, City, State, Zip, Country, p_Declarevalue, p_TempRecords, p_TotalQty, p_SignatureRequiredforDelivery, p_ViewDetail, p_DropShipAddress, null);
        }
        
        /// <remarks/>
        public void get_ShippingChargesWEBAsync(string[] MYArrserviceCode, string Address1, string City, string State, string Zip, string Country, bool p_Declarevalue, string[] p_TempRecords, long p_TotalQty, bool p_SignatureRequiredforDelivery, bool p_ViewDetail, bool p_DropShipAddress, object userState) {
            if ((this.get_ShippingChargesWEBOperationCompleted == null)) {
                this.get_ShippingChargesWEBOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_ShippingChargesWEBOperationCompleted);
            }
            this.InvokeAsync("get_ShippingChargesWEB", new object[] {
                        MYArrserviceCode,
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_Declarevalue,
                        p_TempRecords,
                        p_TotalQty,
                        p_SignatureRequiredforDelivery,
                        p_ViewDetail,
                        p_DropShipAddress}, this.get_ShippingChargesWEBOperationCompleted, userState);
        }
        
        private void Onget_ShippingChargesWEBOperationCompleted(object arg) {
            if ((this.get_ShippingChargesWEBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_ShippingChargesWEBCompleted(this, new get_ShippingChargesWEBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Verify_Address", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Verify_Address(string Address1, string City, string State, string Zip, string Country, bool p_DropShipAddress) {
            object[] results = this.Invoke("Verify_Address", new object[] {
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_DropShipAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Verify_AddressAsync(string Address1, string City, string State, string Zip, string Country, bool p_DropShipAddress) {
            this.Verify_AddressAsync(Address1, City, State, Zip, Country, p_DropShipAddress, null);
        }
        
        /// <remarks/>
        public void Verify_AddressAsync(string Address1, string City, string State, string Zip, string Country, bool p_DropShipAddress, object userState) {
            if ((this.Verify_AddressOperationCompleted == null)) {
                this.Verify_AddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerify_AddressOperationCompleted);
            }
            this.InvokeAsync("Verify_Address", new object[] {
                        Address1,
                        City,
                        State,
                        Zip,
                        Country,
                        p_DropShipAddress}, this.Verify_AddressOperationCompleted, userState);
        }
        
        private void OnVerify_AddressOperationCompleted(object arg) {
            if ((this.Verify_AddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Verify_AddressCompleted(this, new Verify_AddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void get_ShippingChargesCompletedEventHandler(object sender, get_ShippingChargesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_ShippingChargesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_ShippingChargesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void get_ShippingChargesMVCCompletedEventHandler(object sender, get_ShippingChargesMVCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_ShippingChargesMVCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_ShippingChargesMVCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void get_ShippingChargesWEBCompletedEventHandler(object sender, get_ShippingChargesWEBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_ShippingChargesWEBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_ShippingChargesWEBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Verify_AddressCompletedEventHandler(object sender, Verify_AddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Verify_AddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Verify_AddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591